version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    networks:
      - shsinternal

  db:
    image: mariadb:11
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    networks:
      - shsinternal

volumes:
  mariadb_data:

networks:
  shsinternal:
    driver: bridge

