version: '3.8'

services:
  csd_frontend:
    extends:
      file: ./frontend/docker-compose.yaml
      service: csd_frontend

  csd_backend:
    extends:
      file: ./backend/docker-compose.yaml
      service: csd_backend

  csd_database:
    extends:
      file: ./backend/docker-compose.yaml
      service: csd_database

networks:
  csd_net:
    driver: bridge
