version: '3.8'

services:
  frontend:
    extends:
      file: ./frontend/docker-compose.yaml
      service: frontend

  app:
    extends:
      file: ./backend/docker-compose.yaml
      service: app

  db:
    extends:
      file: ./backend/docker-compose.yaml
      service: db

networks:
  csd_net:
    driver: bridge
