version: '3.8'

name: csd-shs

services:
  app:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - "13000:13000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/shelfens
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - csd_net
  db:
    image: mariadb:10.3
    container_name: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
        - csd_net

networks:
  csd_net:
    driver: bridge