version: '3.8'

name: csd-shs

services:
  app:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/shelfens
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      GITHUB_REDIRECT_URI:
      NEXTCLOUD_CLIENT_ID:
      NEXTCLOUD_CLIENT_SECRET:
      NEXTCLOUD_REDIRECT_URI:
      NEXTCLOUD_URL:
      APP_OAUTH2_SUCCESS_REDIRECT_URL:
      APP_OAUTH2_FAIL_REDIRECT_URL:
      APP_FRONTEND_URL:
      APP_AUTH_JWT_SECRET:
    networks:
      - csd_net
  db:
    image: mariadb:10.3
    container_name: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
        - csd_net

networks:
  csd_net:
    driver: bridge