spring:
  application:
    name: webapp
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            authorization-grant-type: authorization_code
            scope: read_user
          nextcloud:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/nextcloud
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
          nextcloud:
            authorization-uri: https://nextcloud.klnsdr.com/apps/oauth2/authorize
            token-uri: https://nextcloud.klnsdr.com/apps/oauth2/api/v1/token
            user-info-uri: https://nextcloud.klnsdr.com/ocs/v2.php/cloud/user?format=json
            user-name-attribute: id
logging:
  level:
    root: INFO
    com.klnsdr.axon: DEBUG
server:
  port: 8080
app:
  oauth2:
    successRedirectUrl:
    failRedirectUrl:
  frontend:
    url:
  auth:
    jwt:
      secret: lsadhflksjahfkjsdhfksdgfkh
      expiration: 10800000 # 3 hours

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/api-docs/swagger-ui.html
    operationsSorter: method