spring:
  application:
    name: webapp
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
server:
  port: 8080
app:
  oauth2:
    successRedirectUrl: http://localhost:8080
    failRedirectUrl: http://localhost:8080/login?error=true
  frontend:
    url:
  auth:
    jwt:
      secret: lsadhflksjahfkjsdhfksdgfkh
      expiration: 10800000 # 3 hours

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/api-docs/swagger-ui.html
    operationsSorter: method