spring:
  application:
    name: webapp
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: client_id
            client-secret: client-secret
            redirect-uri: https://example.com/login/oauth2/code/github
            authorization-grant-type: authorization_code
            scope: read_user
          nextcloud:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: https://example.com/login/oauth2/code/nextcloud
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
          nextcloud:
            authorization-uri: https://nextcloud.example.com/apps/oauth2/authorize
            token-uri: https://nextcloud.example.com/apps/oauth2/api/v1/token
            user-info-uri: https://nextcloud.example.com/ocs/v2.php/cloud/user?format=json
            user-name-attribute: id
logging:
  level:
    root: INFO
    com.klnsdr.axon: DEBUG
server:
  port: 0
app:
  oauth2:
    successRedirectUrl: https://example.com/success
    failRedirectUrl: https://example.com/fail
  frontend:
    url: https://example.com
  auth:
    jwt:
      secret: secret
      expiration: 60000 # 1 minute for testing purposes

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/api-docs/swagger-ui.html
    operationsSorter: method
