spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: webapp
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: read_user
          nextcloud:
            client-id: ${NEXTCLOUD_CLIENT_ID}
            client-secret: ${NEXTCLOUD_CLIENT_SECRET}
            redirect-uri: ${NEXTCLOUD_REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
          nextcloud:
            authorization-uri: ${NEXTCLOUD_URL}/apps/oauth2/authorize
            token-uri: ${NEXTCLOUD_URL}/apps/oauth2/api/v1/token
            user-info-uri: ${NEXTCLOUD_URL}/ocs/v2.php/cloud/user?format=json
            user-name-attribute: id
logging:
  level:
    root: WARN
    com.klnsdr.axon: WARN
server:
  port: 8080
app:
  oauth2:
    successRedirectUrl: ${APP_OAUTH2_SUCCESS_REDIRECT_URL}
    failRedirectUrl: ${APP_OAUTH2_FAIL_REDIRECT_URL}
  frontend:
    url: ${APP_FRONTEND_URL}
  auth:
    jwt:
      secret: ${APP_AUTH_JWT_SECRET}
      expiration: 10800000 # 3 hours

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/api-docs/swagger-ui.html
    operationsSorter: method
